apiVersion: v1
kind: Service
metadata:
  name: tasty-service
  labels:
    app: tasty-service
spec:
  type: ClusterIP
  selector:
    app: tasty-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001